import React, { useEffect } from 'react';
import mascot from '../../assets/icon-mascot.png';

const SECTIONS = [
  {
    heading: null,
    body: `Notifybear is an AI-powered notification filtering and prioritization application that helps You manage notifications from apps You select on Your Android device. We access notification data only to provide the core functionality of filtering, prioritizing, and delivering personalized notification insights.\n\nWe use Your Personal Data to provide, operate, and improve the Service. By using the Service, You agree to the collection and use of information in accordance with this Privacy Policy.`,
  },
  {
    heading: 'Interpretation and Definitions',
    subsections: [
      {
        subheading: 'Interpretation',
        body: `The words whose initial letters are capitalized have meanings defined under the following conditions. The following definitions shall have the same meaning regardless of whether they appear in singular or in plural.`,
      },
      {
        subheading: 'Definitions',
        body: `For the purposes of this Privacy Policy:`,
        list: [
          `Account means a unique account created for You to access our Service or parts of our Service.`,
          `Affiliate means an entity that controls, is controlled by, or is under common control with a party.`,
          `Application refers to Notifybear, the software program provided by the Company.`,
          `Company (referred to as either "the Company", "We", "Us" or "Our" in this Privacy Policy) refers to Notifybear LLC, 2115 Summit Avenue, Saint Paul, MN, 55105.`,
          `Country refers to: Minnesota, United States and India.`,
          `Device means any device that can access the Service such as a computer, a cell phone or a digital tablet.`,
          `Personal Data (or "Personal Information") is any information that relates to an identified or identifiable individual. We use "Personal Data" and "Personal Information" interchangeably unless a law uses a specific term.`,
          `Service refers to the Application.`,
          `Service Provider means any natural or legal person who processes the data on behalf of the Company. It refers to third-party companies or individuals employed by the Company to facilitate the Service, to provide the Service on behalf of the Company, to perform services related to the Service or to assist the Company in analyzing how the Service is used.`,
          `Usage Data refers to data collected automatically, either generated by the use of the Service or from the Service infrastructure itself.`,
          `You means the individual accessing or using the Service, or the company, or other legal entity on behalf of which such individual is accessing or using the Service, as applicable.`,
        ],
      },
    ],
  },
  {
    heading: 'Collecting and Using Your Personal Data',
    subsections: [
      {
        subheading: 'Types of Data Collected',
        body: null,
        nested: [
          {
            subheading: 'Personal Data',
            body: `While using Our Service, We may ask You to provide Us with certain personally identifiable information that can be used to contact or identify You. Personally identifiable information may include, but is not limited to:`,
            list: [
              'Email address',
              'First name and last name (optional)',
              'Account identifiers',
              'Notification Data',
            ],
          },
          {
            subheading: 'Notification Data',
            body: `To provide the core functionality of Notifybear, We access notifications from applications that You explicitly authorize through Android notification access permissions.\n\nThis may include:`,
            list: [
              'Notification text and title',
              'Application name and identifier',
              'Sender name (if available)',
              'Notification timestamps',
              'Notification metadata required for filtering',
            ],
            after: `Notifybear processes notifications primarily on Your Device. Only limited derived features or signals necessary to improve filtering accuracy and service performance may be transmitted to Our servers. Notifybear does not continuously store complete notification histories on Our servers.`,
          },
          {
            subheading: 'Usage Data',
            body: `Usage Data is collected automatically when using the Service.\n\nUsage Data may include information such as:`,
            list: [
              "Your Device's Internet Protocol address (IP address)",
              'Device type and model',
              'Android operating system version',
              'Application version',
              'Diagnostic data such as crash reports',
              'Feature usage statistics',
            ],
            after: `Notifybear uses internal analytics systems to understand Service usage and improve functionality. We do not use third-party advertising trackers.`,
          },
        ],
      },
    ],
  },
  {
    heading: 'Use of Your Personal Data',
    body: `The Company may use Personal Data for the following purposes:`,
    list: [
      `To provide and maintain our Service, including notification filtering, prioritization, and personalization.`,
      `To manage Your Account: to manage Your registration as a user of the Service. The Personal Data You provide can give You access to different functionalities of the Service that are available to You as a registered user.`,
      `To perform core Service functionality: including analyzing notification metadata and improving filtering accuracy using our proprietary models.`,
      `To train and improve our AI models: The collected notification data and user interactions are used to train our AI algorithms to make the model more efficient and accurate for You and future users. This continuous learning process helps us deliver better notification filtering and prioritization over time.`,
      `To contact You: To contact You by email, telephone calls, SMS, or other equivalent forms of electronic communication, such as a mobile application's push notifications regarding updates or informative communications regarding updates, security alerts, or important service-related information.`,
      `To improve the Service: including improving model accuracy, usability, reliability, and performance.`,
      `To manage Your requests: To attend and manage Your requests to Us.`,
      `For business transfers: We may use Your Personal Data to evaluate or conduct a merger, divestiture, restructuring, reorganization, dissolution, or other sale or transfer of some or all of Our assets, whether as a going concern or as part of bankruptcy, liquidation, or similar proceeding, in which Personal Data held by Us about our Service users is among the assets transferred.`,
      `For security purposes: including preventing misuse, fraud, or unauthorized access.`,
      `For other purposes: We may use Your information for other purposes, such as data analysis, identifying usage trends, determining the effectiveness of our promotional campaigns and to evaluate and improve our Service, products, services, marketing and your experience.`,
    ],
    after: `We may share Your Personal Data in the following situations:`,
    afterList: [
      `With Service Providers: We may share Your Personal Data with Service Providers to monitor and analyze the use of our Service, to contact You.`,
      `For business transfers: We may share or transfer Your Personal Data in connection with, or during negotiations of, any merger, sale of Company assets, financing, or acquisition of all or a portion of Our business to another company.`,
      `With Affiliates: We may share Your Personal Data with Our affiliates, in which case we will require those affiliates to honor this Privacy Policy. Affiliates include Our parent company and any other subsidiaries, joint venture partners or other companies that We control or that are under common control with Us.`,
      `With business partners: We may share Your Personal Data with Our business partners to offer You certain products, services or promotions.`,
      `With Your consent: We may disclose Your Personal Data for any other purpose with Your consent.`,
    ],
  },
  {
    heading: 'Retention of Your Personal Data',
    body: `The Company will retain Your Personal Data only for as long as is necessary for the purposes set out in this Privacy Policy. We will retain and use Your Personal Data to the extent necessary to comply with our legal obligations (for example, if We are required to retain Your data to comply with applicable laws), resolve disputes, and enforce our legal agreements and policies.\n\nWhere possible, We apply shorter retention periods and/or reduce identifiability by deleting, aggregating, or anonymizing data. We apply different retention periods to different categories of Personal Data based on the purpose of processing and legal obligations:`,
    list: [
      `Account Information — User Accounts: retained for the duration of your account relationship plus up to 24 months after account closure.`,
      `Usage Data — Application usage statistics: up to 24 months.`,
      `Server logs (IP addresses, access times): up to 24 months for security monitoring and troubleshooting.`,
      `Notification-derived data — minimal derived features may be retained temporarily for model improvement and service reliability.`,
    ],
    after: `We may retain Personal Data beyond the stated periods for legal obligation, legal claims, your explicit request, or due to technical limitations in backup systems.\n\nWhen retention periods expire, We securely delete or anonymize Personal Data. In some cases, anonymized statistical data that cannot be linked back to You may be retained indefinitely for research and analytics.`,
  },
  {
    heading: 'Transfer of Your Personal Data',
    body: `Your information, including Personal Data, is processed at the Company's operating offices and in any other places where the parties involved in the processing are located. It means that this information may be transferred to and maintained on computers located outside of Your state, province, country or other governmental jurisdiction where the data protection laws may differ from those from Your jurisdiction.\n\nWhere required by applicable law, We will ensure that international transfers of Your Personal Data are subject to appropriate safeguards. The Company will take all steps reasonably necessary to ensure that Your data is treated securely and in accordance with this Privacy Policy and no transfer of Your Personal Data will take place to an organization or a country unless there are adequate controls in place.`,
  },
  {
    heading: 'Delete Your Personal Data',
    body: `You have the right to delete or request that We assist in deleting the Personal Data that We have collected about You.\n\nYou may:`,
    list: [
      'Delete Your account through the Application',
      'Disable notification access through Android settings',
      'Contact Us to request deletion',
    ],
    after: `We may retain certain information if required by law or for legitimate business purposes. Please note that We may need to retain certain information when we have a legal obligation or lawful basis to do so.\n\nWhen you delete your account or request data deletion, the reason for deletion (if provided) may be logged and retained for business purposes, including understanding user feedback, improving our Service, and analyzing usage patterns.`,
  },
  {
    heading: 'Disclosure of Your Personal Data',
    subsections: [
      {
        subheading: 'Business Transactions',
        body: `If the Company is involved in a merger, acquisition or asset sale, Your Personal Data may be transferred. We will provide notice before Your Personal Data is transferred and becomes subject to a different Privacy Policy.`,
      },
      {
        subheading: 'Law Enforcement',
        body: `Under certain circumstances, the Company may be required to disclose Your Personal Data if required to do so by law or in response to valid requests by public authorities (e.g. a court or a government agency).`,
      },
      {
        subheading: 'Other Legal Requirements',
        body: `The Company may disclose Your Personal Data in the good faith belief that such action is necessary to:`,
        list: [
          'Comply with a legal obligation',
          'Protect and defend the rights or property of the Company',
          'Prevent or investigate possible wrongdoing in connection with the Service',
          'Protect the personal safety of Users of the Service or the public',
          'Protect against legal liability',
        ],
      },
    ],
  },
  {
    heading: 'Security of Your Personal Data',
    body: `The security of Your Personal Data is important to Us, but remember that no method of transmission over the Internet, or method of electronic storage is 100% secure. While We strive to use commercially reasonable means to protect Your Personal Data, We cannot guarantee its absolute security.`,
  },
  {
    heading: "Children's Privacy",
    body: `Our Service does not address anyone under the age of 16. We do not knowingly collect personally identifiable information from anyone under the age of 16. If You are a parent or guardian and You are aware that Your child has provided Us with Personal Data, please contact Us. If We become aware that We have collected Personal Data from anyone under the age of 16 without verification of parental consent, We take steps to remove that information from Our servers.\n\nIf We need to rely on consent as a legal basis for processing Your information and Your country requires consent from a parent, We may require Your parent's consent before We collect and use that information.`,
  },
  {
    heading: 'Links to Other Websites',
    body: `Our Service may contain links to other websites that are not operated by Us. If You click on a third party link, You will be directed to that third party's site. We strongly advise You to review the Privacy Policy of every site You visit.\n\nWe have no control over and assume no responsibility for the content, privacy policies or practices of any third party sites or services.`,
  },
  {
    heading: 'Changes to this Privacy Policy',
    body: `We may update Our Privacy Policy from time to time. We will notify You of any changes by posting the new Privacy Policy on this page.\n\nWe will let You know via email and/or a prominent notice on Our Service, prior to the change becoming effective and update the "Last updated" date at the top of this Privacy Policy.\n\nYou are advised to review this Privacy Policy periodically for any changes. Changes to this Privacy Policy are effective when they are posted on this page.`,
  },
  {
    heading: 'Contact Us',
    body: `If you have any questions about this Privacy Policy, You can contact us:`,
    list: ['By email: support@notifybear.com'],
  },
];

function Paragraph({ text }) {
  return text.split('\n\n').map((para, i) => (
    <p key={i} style={{ margin: '0 0 14px', lineHeight: 1.75, color: '#444' }}>
      {para}
    </p>
  ));
}

function BulletList({ items }) {
  return (
    <ul style={{ margin: '12px 0 16px 0', paddingLeft: 24 }}>
      {items.map((item, i) => (
        <li key={i} style={{ marginBottom: 8, lineHeight: 1.7, color: '#444' }}>
          {item}
        </li>
      ))}
    </ul>
  );
}

function renderSection(section, depth = 0) {
  return (
    <div key={section.heading || 'intro'} style={{ marginBottom: depth === 0 ? 48 : 28 }}>
      {section.heading && (
        <h2 style={{
          fontSize: depth === 0 ? '1.35rem' : '1.05rem',
          fontWeight: 700,
          color: '#111',
          letterSpacing: '-0.02em',
          marginBottom: 12,
          marginTop: depth === 0 ? 0 : 4,
        }}>
          {section.heading}
        </h2>
      )}

      {section.body && <Paragraph text={section.body} />}
      {section.list && <BulletList items={section.list} />}
      {section.after && <Paragraph text={section.after} />}
      {section.afterList && <BulletList items={section.afterList} />}

      {section.subsections && section.subsections.map((sub, i) => (
        <div key={i} style={{ marginBottom: 20 }}>
          <h3 style={{
            fontSize: '1.0rem',
            fontWeight: 700,
            color: '#222',
            marginBottom: 8,
            letterSpacing: '-0.01em',
          }}>
            {sub.subheading}
          </h3>
          {sub.body && <Paragraph text={sub.body} />}
          {sub.list && <BulletList items={sub.list} />}
          {sub.after && <Paragraph text={sub.after} />}

          {sub.nested && sub.nested.map((nested, j) => (
            <div key={j} style={{ marginBottom: 20, paddingLeft: 16, borderLeft: '2px solid #e5e7eb' }}>
              <h4 style={{
                fontSize: '0.9rem',
                fontWeight: 700,
                color: '#333',
                marginBottom: 8,
                letterSpacing: '-0.005em',
              }}>
                {nested.subheading}
              </h4>
              {nested.body && <Paragraph text={nested.body} />}
              {nested.list && <BulletList items={nested.list} />}
              {nested.after && <Paragraph text={nested.after} />}
            </div>
          ))}
        </div>
      ))}
    </div>
  );
}

export default function PrivacyPolicyPage({ onBack }) {
  useEffect(() => {
    window.scrollTo({ top: 0, behavior: 'smooth' });
  }, []);

  return (
    <div style={{ minHeight: '100vh', background: '#fff', fontFamily: 'inherit' }}>
      {/* Top bar */}
      <div style={{
        position: 'sticky',
        top: 0,
        zIndex: 50,
        background: 'rgba(255,255,255,0.92)',
        backdropFilter: 'blur(12px)',
        borderBottom: '1px solid #e5e7eb',
        padding: '0 24px',
        height: 60,
        display: 'flex',
        alignItems: 'center',
        justifyContent: 'space-between',
      }}>
        <div style={{ display: 'flex', alignItems: 'center', gap: 8 }}>
          <img src={mascot} alt="notifybear" style={{ width: 26, height: 26, objectFit: 'contain' }} />
          <span style={{ fontWeight: 700, fontSize: '1rem', color: '#111', letterSpacing: '-0.01em' }}>notifyBear</span>
        </div>
        <button
          onClick={onBack}
          style={{
            display: 'flex',
            alignItems: 'center',
            gap: 6,
            padding: '7px 16px',
            borderRadius: 999,
            border: '1px solid #e0e0e0',
            background: '#fff',
            color: '#333',
            fontSize: '0.8rem',
            fontWeight: 600,
            cursor: 'pointer',
            transition: 'background 0.15s',
          }}
          onMouseOver={(e) => e.currentTarget.style.background = '#f5f5f5'}
          onMouseOut={(e) => e.currentTarget.style.background = '#fff'}
        >
          ← Back
        </button>
      </div>

      {/* Content */}
      <div style={{
        maxWidth: 720,
        margin: '0 auto',
        padding: '64px 32px 96px',
      }}>
        {/* Title block */}
        <div style={{ marginBottom: 48, paddingBottom: 32, borderBottom: '1px solid #e5e7eb' }}>
          <h1 style={{
            fontSize: 'clamp(2rem, 5vw, 2.75rem)',
            fontWeight: 800,
            color: '#111',
            letterSpacing: '-0.03em',
            lineHeight: 1.1,
            marginBottom: 12,
          }}>
            Privacy Policy
          </h1>
          <p style={{ fontSize: '0.875rem', color: '#888', margin: 0 }}>
            Last updated: February 26, 2026
          </p>
        </div>

        {/* Intro blurb */}
        <p style={{ fontSize: '0.975rem', color: '#555', lineHeight: 1.75, marginBottom: 48 }}>
          This Privacy Policy describes Our policies and procedures on the collection, use, and disclosure of Your information when You use the Service and tells You about Your privacy rights and how the law protects You.
        </p>

        {/* Sections */}
        <div style={{ fontSize: '0.9375rem' }}>
          {SECTIONS.map((section) => renderSection(section))}
        </div>
      </div>

      {/* Footer */}
      <div style={{
        borderTop: '1px solid #e5e7eb',
        padding: '28px 32px',
        display: 'flex',
        alignItems: 'center',
        justifyContent: 'center',
        gap: 8,
      }}>
        <img src={mascot} alt="notifybear" style={{ width: 18, height: 18, objectFit: 'contain', opacity: 0.5 }} />
        <p style={{ fontSize: '0.8rem', color: '#aaa', margin: 0 }}>
          © {new Date().getFullYear()} NotifyBear LLC. All rights reserved.
        </p>
      </div>
    </div>
  );
}
